name: Verify Pep8
on:
  pull_request:
    branches: [main]
    paths: ['python/*.py']

jobs:
  verify:
    name: Verify Python Indent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
