name: Verify Pep8
on:
  pull_request:
    branches: [main]
    paths: ['python/*.py']

jobs:
  verify:
    name: Verify Python Indent
    runs-on: ubuntu-latest
    env:
      HOOK_URL: https://nhnent.dooray.com/services/1387695619080878080/2697784993322248692/z0jwkVQFRtWYghBmuxi1fQ
    steps:
      - uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
      - name: Dooray msg on failure
        if: failure()
        uses: ./.github/actions/dooray/
        with:
          botName: 'VerifierBot'
          botIconImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNmfE2CWjH0wRFNRareaLCVps6hx8nqMG1Pw&s'
          text: 'Wrong content detected!'
